// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArZqhqGm_6W_FiZa6UvLA3r0RwlToF2wU',
    appId: '1:355442456916:web:fd39abdf721258538cf0c1',
    messagingSenderId: '355442456916',
    projectId: 'flutter-test-ceb11',
    authDomain: 'flutter-test-ceb11.firebaseapp.com',
    storageBucket: 'flutter-test-ceb11.firebasestorage.app',
    measurementId: 'G-D7C22SFSRS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLN1_Ry-lCIWGwD3pBLARRfa1OdHmDYBA',
    appId: '1:355442456916:android:e624dab591ac70e88cf0c1',
    messagingSenderId: '355442456916',
    projectId: 'flutter-test-ceb11',
    storageBucket: 'flutter-test-ceb11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN4luTe6PbCXEErSqxd0wB4PE1CIEO2DU',
    appId: '1:355442456916:ios:bfdf979e0e05e4f48cf0c1',
    messagingSenderId: '355442456916',
    projectId: 'flutter-test-ceb11',
    storageBucket: 'flutter-test-ceb11.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN4luTe6PbCXEErSqxd0wB4PE1CIEO2DU',
    appId: '1:355442456916:ios:bfdf979e0e05e4f48cf0c1',
    messagingSenderId: '355442456916',
    projectId: 'flutter-test-ceb11',
    storageBucket: 'flutter-test-ceb11.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArZqhqGm_6W_FiZa6UvLA3r0RwlToF2wU',
    appId: '1:355442456916:web:2be91b1e40d22e068cf0c1',
    messagingSenderId: '355442456916',
    projectId: 'flutter-test-ceb11',
    authDomain: 'flutter-test-ceb11.firebaseapp.com',
    storageBucket: 'flutter-test-ceb11.firebasestorage.app',
    measurementId: 'G-90KELPS92P',
  );
}
